// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCompany.Transfers.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyCompany.Transfers.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224180804_SentEmailHistoryAdded")]
    partial class SentEmailHistoryAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyCompany.Transfers.Domain.Accounts.AccountDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Algorithm")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MinLength")
                        .HasColumnType("integer");

                    b.Property<int>("Normalize")
                        .HasColumnType("integer");

                    b.Property<string>("Regex")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccountDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1744710c-a062-4c33-8077-756db29a06b6"),
                            Algorithm = 0,
                            Code = "PHONE",
                            MaxLength = 15,
                            MinLength = 9,
                            Normalize = 2,
                            Regex = "^\\d{9,15}$"
                        },
                        new
                        {
                            Id = new Guid("3fcdac91-5f18-425b-945f-169d539b6bde"),
                            Algorithm = 1,
                            Code = "PAN",
                            MaxLength = 16,
                            MinLength = 16,
                            Normalize = 2,
                            Regex = "^\\d{16}$"
                        });
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Agents.Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Balances")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PartnerEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("Asia/Dushanbe");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Agents.AgentCurrencyAccess", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.HasKey("AgentId", "Currency");

                    b.ToTable("AgentCurrencyAccess", (string)null);
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Agents.AgentServiceAccess", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ServiceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<long>("FeeFlatMinor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<int>("FeePermille")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("AgentId", "ServiceId");

                    b.ToTable("AgentServiceAccess", (string)null);
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Agents.SentCredentialsEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("SentCredentialsEmails", (string)null);
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Agents.Terminal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.ToTable("Terminals");
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Providers.Provider", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("FeePermille")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("TimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.HasKey("Id");

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Rates.FxRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(20,8)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("manual");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "BaseCurrency", "QuoteCurrency")
                        .IsUnique();

                    b.ToTable("FxRates", (string)null);
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Services.ParamDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Regex")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ParamDefinition", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "100",
                            Active = true,
                            Code = "sender_doc_type",
                            Name = "Тип удостоверяющего документа плательщика"
                        },
                        new
                        {
                            Id = "101",
                            Active = true,
                            Code = "sender_doc_number",
                            Name = "Серия и номер документа",
                            Regex = "^[A-Z0-9]+$"
                        },
                        new
                        {
                            Id = "102",
                            Active = true,
                            Code = "sender_phone",
                            Name = "Номер мобильного телефона плательщика"
                        },
                        new
                        {
                            Id = "103",
                            Active = true,
                            Code = "sender_doc_department_code",
                            Name = "Код подразделения, выдавшего паспорт"
                        },
                        new
                        {
                            Id = "104",
                            Active = true,
                            Code = "sender_residency",
                            Name = "Резидентство плательщика: 1 – резидент РТ, 0 – нерезидент.",
                            Regex = "^(1{1}|2{1})$"
                        },
                        new
                        {
                            Id = "105",
                            Active = true,
                            Code = "account_number",
                            Name = "Номер счёта плательщика"
                        },
                        new
                        {
                            Id = "106",
                            Active = true,
                            Code = "sender_doc_issue_date",
                            Name = "Дата выдачи документа",
                            Regex = "^(19|20)\\d{2}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$"
                        },
                        new
                        {
                            Id = "107",
                            Active = true,
                            Code = "sender_fullname_cyr",
                            Name = "Полное ФИО плательщика (кириллицей)",
                            Regex = "^[А-ЯЁа-яё]+(?:-[А-ЯЁа-яё]+)*\\s[А-ЯЁа-яё]+(?:-[А-ЯЁа-яё]+)*(?:\\s[А-ЯЁа-яё]+(?:-[А-ЯЁа-яё]+)*)?$"
                        },
                        new
                        {
                            Id = "108",
                            Active = true,
                            Code = "sender_firstname_cyr",
                            Name = "Фамилия плательщика (кириллицей)",
                            Regex = "^[А-Яа-яЁё\\s\\-]+$"
                        },
                        new
                        {
                            Id = "109",
                            Active = true,
                            Code = "sender_lastname_cyr",
                            Name = "Имя плательщика (кириллицей)",
                            Regex = "^[А-Яа-яЁё\\s\\-]+$"
                        },
                        new
                        {
                            Id = "110",
                            Active = true,
                            Code = "sender_middlename_cyr",
                            Name = "Отчество плательщика (кириллицей)",
                            Regex = "^[А-Яа-яЁё\\s\\-]+$"
                        },
                        new
                        {
                            Id = "111",
                            Active = true,
                            Code = "receiver_fullname_cyr",
                            Name = "Полное ФИО получателя (кириллицей)",
                            Regex = "^[А-ЯЁа-яё]+(?:-[А-ЯЁа-яё]+)*\\s[А-ЯЁа-яё]+(?:-[А-ЯЁа-яё]+)*(?:\\s[А-ЯЁа-яё]+(?:-[А-ЯЁа-яё]+)*)?$"
                        },
                        new
                        {
                            Id = "112",
                            Active = true,
                            Code = "receiver_firstname_cyr",
                            Name = "Имя получателя (кириллицей)",
                            Regex = "^[А-Яа-яЁё\\s\\-]+$"
                        },
                        new
                        {
                            Id = "113",
                            Active = true,
                            Code = "receiver_lastname_cyr",
                            Name = "Фамилия получателя (кириллицей)",
                            Regex = "^[А-Яа-яЁё\\s\\-]+$"
                        },
                        new
                        {
                            Id = "114",
                            Active = true,
                            Code = "receiver_middlename_cyr",
                            Name = "Отчество получателя (кириллицей)",
                            Regex = "^[А-Яа-яЁё\\s\\-]+$"
                        },
                        new
                        {
                            Id = "115",
                            Active = true,
                            Code = "sender_fullname",
                            Name = "Полное ФИО плательщика \"Фамилия Имя Отчество\"",
                            Regex = "^[A-Za-z]+(?:-[A-Za-z]+)*\\s[A-Za-z]+(?:-[A-Za-z]+)*(?:\\s[A-Za-z]+(?:-[A-Za-z]+)*)?$"
                        },
                        new
                        {
                            Id = "116",
                            Active = true,
                            Code = "sender_lastname",
                            Name = "Фамилия плательщика",
                            Regex = "^[A-Za-z\\s\\-]+$"
                        },
                        new
                        {
                            Id = "117",
                            Active = true,
                            Code = "sender_firstname",
                            Name = "Имя плательщика",
                            Regex = "^[A-Za-z\\s\\-]+$"
                        },
                        new
                        {
                            Id = "118",
                            Active = true,
                            Code = "sender_middlename",
                            Name = "Отчество плательщика",
                            Regex = "^[A-Za-z\\s\\-]+$"
                        },
                        new
                        {
                            Id = "119",
                            Active = true,
                            Code = "sender_doc_issuer",
                            Name = "Орган, выдавший документ"
                        },
                        new
                        {
                            Id = "120",
                            Active = true,
                            Code = "sender_birth_place",
                            Name = "Место рождения плательщика"
                        },
                        new
                        {
                            Id = "121",
                            Active = true,
                            Code = "sender_citizenship",
                            Name = "Гражданство плательщика"
                        },
                        new
                        {
                            Id = "122",
                            Active = true,
                            Code = "sender_registration_address",
                            Name = "Адрес регистрации: страна, регион, город, улица, дом, квартира и т.п."
                        },
                        new
                        {
                            Id = "123",
                            Active = true,
                            Code = "receiver_fullname",
                            Name = "Полное ФИО получателя",
                            Regex = "^[A-Za-z]+(?:-[A-Za-z]+)*\\s[A-Za-z]+(?:-[A-Za-z]+)*(?:\\s[A-Za-z]+(?:-[A-Za-z]+)*)?$"
                        },
                        new
                        {
                            Id = "124",
                            Active = true,
                            Code = "receiver_firstname",
                            Name = "Имя получателя",
                            Regex = "^[A-Za-z\\s\\-]+$"
                        },
                        new
                        {
                            Id = "125",
                            Active = true,
                            Code = "receiver_lastname",
                            Name = "Фамилия получателя",
                            Regex = "^[A-Za-z\\s\\-]+$"
                        },
                        new
                        {
                            Id = "126",
                            Active = true,
                            Code = "receiver_middlename",
                            Name = "Отчество получателя",
                            Regex = "^[A-Za-z\\s\\-]+$"
                        },
                        new
                        {
                            Id = "127",
                            Active = true,
                            Code = "sender_birth_date",
                            Name = "Дата рождения плательщика",
                            Regex = "^(19|20)\\d{2}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$"
                        });
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Services.Service", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Guid>("AccountDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedCurrencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FxRounding")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("MaxAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("MinAmountMinor")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProviderServiceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Services.ServiceParamDefinition", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ParameterId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.HasKey("ServiceId", "ParameterId");

                    b.HasIndex("ParameterId");

                    b.ToTable("ServiceParamDefinition", (string)null);
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Transfers.Outbox", b =>
                {
                    b.Property<Guid>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorDescription")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("NumId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("PreparedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderCode")
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderServiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderTransferId")
                        .HasColumnType("text");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("_parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Parameters");

                    b.Property<string>("_provReceivedParams")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ProvReceivedParams");

                    b.HasKey("TransferId");

                    b.HasIndex("AgentId", "ExternalId")
                        .IsUnique();

                    b.ToTable("Outboxes");
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Transfers.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorDescription")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("NumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NumId"));

                    b.Property<DateTimeOffset?>("PreparedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderCode")
                        .HasColumnType("text");

                    b.Property<string>("ProviderTransferId")
                        .HasColumnType("text");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("_parameters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Parameters");

                    b.Property<string>("_provReceivedParams")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ProvReceivedParams");

                    b.HasKey("Id");

                    b.HasIndex("NumId")
                        .IsUnique();

                    b.HasIndex("AgentId", "ExternalId")
                        .IsUnique();

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Services.ServiceParamDefinition", b =>
                {
                    b.HasOne("MyCompany.Transfers.Domain.Services.ParamDefinition", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyCompany.Transfers.Domain.Services.Service", null)
                        .WithMany("Parameters")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Transfers.Outbox", b =>
                {
                    b.OwnsOne("MyCompany.Transfers.Domain.Transfers.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("OutboxTransferId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.Property<long>("Minor")
                                .HasColumnType("bigint")
                                .HasColumnName("AmountMinor");

                            b1.HasKey("OutboxTransferId");

                            b1.ToTable("Outboxes");

                            b1.WithOwner()
                                .HasForeignKey("OutboxTransferId");
                        });

                    b.OwnsOne("MyCompany.Transfers.Domain.Transfers.Quote", "CurrentQuote", b1 =>
                        {
                            b1.Property<Guid>("OutboxTransferId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("ExchangeRate")
                                .HasColumnType("numeric(20,8)")
                                .HasColumnName("ExchangeRate");

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("QuoteExpiresAtUtc");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("QuoteId");

                            b1.Property<DateTimeOffset?>("RateTimestampUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("RateTimestampUtc");

                            b1.HasKey("OutboxTransferId");

                            b1.ToTable("Outboxes");

                            b1.WithOwner()
                                .HasForeignKey("OutboxTransferId");

                            b1.OwnsOne("MyCompany.Transfers.Domain.Transfers.Money", "CreditedAmount", b2 =>
                                {
                                    b2.Property<Guid>("QuoteOutboxTransferId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("CreditedCurrency");

                                    b2.Property<long>("Minor")
                                        .HasColumnType("bigint")
                                        .HasColumnName("CreditedMinor");

                                    b2.HasKey("QuoteOutboxTransferId");

                                    b2.ToTable("Outboxes");

                                    b2.WithOwner()
                                        .HasForeignKey("QuoteOutboxTransferId");
                                });

                            b1.OwnsOne("MyCompany.Transfers.Domain.Transfers.Money", "Fee", b2 =>
                                {
                                    b2.Property<Guid>("QuoteOutboxTransferId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("FeeCurrency");

                                    b2.Property<long>("Minor")
                                        .HasColumnType("bigint")
                                        .HasColumnName("FeeMinor");

                                    b2.HasKey("QuoteOutboxTransferId");

                                    b2.ToTable("Outboxes");

                                    b2.WithOwner()
                                        .HasForeignKey("QuoteOutboxTransferId");
                                });

                            b1.OwnsOne("MyCompany.Transfers.Domain.Transfers.Money", "ProviderFee", b2 =>
                                {
                                    b2.Property<Guid>("QuoteOutboxTransferId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("ProviderFeeCurrency");

                                    b2.Property<long>("Minor")
                                        .HasColumnType("bigint")
                                        .HasColumnName("ProviderFeeMinor");

                                    b2.HasKey("QuoteOutboxTransferId");

                                    b2.ToTable("Outboxes");

                                    b2.WithOwner()
                                        .HasForeignKey("QuoteOutboxTransferId");
                                });

                            b1.OwnsOne("MyCompany.Transfers.Domain.Transfers.Money", "Total", b2 =>
                                {
                                    b2.Property<Guid>("QuoteOutboxTransferId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("TotalCurrency");

                                    b2.Property<long>("Minor")
                                        .HasColumnType("bigint")
                                        .HasColumnName("TotalMinor");

                                    b2.HasKey("QuoteOutboxTransferId");

                                    b2.ToTable("Outboxes");

                                    b2.WithOwner()
                                        .HasForeignKey("QuoteOutboxTransferId");
                                });

                            b1.Navigation("CreditedAmount")
                                .IsRequired();

                            b1.Navigation("Fee")
                                .IsRequired();

                            b1.Navigation("ProviderFee")
                                .IsRequired();

                            b1.Navigation("Total")
                                .IsRequired();
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("CurrentQuote");
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Transfers.Transfer", b =>
                {
                    b.OwnsOne("MyCompany.Transfers.Domain.Transfers.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransferId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.Property<long>("Minor")
                                .HasColumnType("bigint")
                                .HasColumnName("AmountMinor");

                            b1.HasKey("TransferId");

                            b1.ToTable("Transfers");

                            b1.WithOwner()
                                .HasForeignKey("TransferId");
                        });

                    b.OwnsOne("MyCompany.Transfers.Domain.Transfers.Quote", "CurrentQuote", b1 =>
                        {
                            b1.Property<Guid>("TransferId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("ExchangeRate")
                                .HasColumnType("numeric(20,8)")
                                .HasColumnName("ExchangeRate");

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("QuoteExpiresAtUtc");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("QuoteId");

                            b1.Property<DateTimeOffset?>("RateTimestampUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("RateTimestampUtc");

                            b1.HasKey("TransferId");

                            b1.ToTable("Transfers");

                            b1.WithOwner()
                                .HasForeignKey("TransferId");

                            b1.OwnsOne("MyCompany.Transfers.Domain.Transfers.Money", "CreditedAmount", b2 =>
                                {
                                    b2.Property<Guid>("QuoteTransferId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("CreditedCurrency");

                                    b2.Property<long>("Minor")
                                        .HasColumnType("bigint")
                                        .HasColumnName("CreditedMinor");

                                    b2.HasKey("QuoteTransferId");

                                    b2.ToTable("Transfers");

                                    b2.WithOwner()
                                        .HasForeignKey("QuoteTransferId");
                                });

                            b1.OwnsOne("MyCompany.Transfers.Domain.Transfers.Money", "Fee", b2 =>
                                {
                                    b2.Property<Guid>("QuoteTransferId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("FeeCurrency");

                                    b2.Property<long>("Minor")
                                        .HasColumnType("bigint")
                                        .HasColumnName("FeeMinor");

                                    b2.HasKey("QuoteTransferId");

                                    b2.ToTable("Transfers");

                                    b2.WithOwner()
                                        .HasForeignKey("QuoteTransferId");
                                });

                            b1.OwnsOne("MyCompany.Transfers.Domain.Transfers.Money", "ProviderFee", b2 =>
                                {
                                    b2.Property<Guid>("QuoteTransferId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("ProviderFeeCurrency");

                                    b2.Property<long>("Minor")
                                        .HasColumnType("bigint")
                                        .HasColumnName("ProviderFeeMinor");

                                    b2.HasKey("QuoteTransferId");

                                    b2.ToTable("Transfers");

                                    b2.WithOwner()
                                        .HasForeignKey("QuoteTransferId");
                                });

                            b1.OwnsOne("MyCompany.Transfers.Domain.Transfers.Money", "Total", b2 =>
                                {
                                    b2.Property<Guid>("QuoteTransferId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("TotalCurrency");

                                    b2.Property<long>("Minor")
                                        .HasColumnType("bigint")
                                        .HasColumnName("TotalMinor");

                                    b2.HasKey("QuoteTransferId");

                                    b2.ToTable("Transfers");

                                    b2.WithOwner()
                                        .HasForeignKey("QuoteTransferId");
                                });

                            b1.Navigation("CreditedAmount")
                                .IsRequired();

                            b1.Navigation("Fee")
                                .IsRequired();

                            b1.Navigation("ProviderFee")
                                .IsRequired();

                            b1.Navigation("Total")
                                .IsRequired();
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("CurrentQuote");
                });

            modelBuilder.Entity("MyCompany.Transfers.Domain.Services.Service", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
